"""add is_admin to users and cover_letters table

Revision ID: 557e476656e7
Revises: 
Create Date: 2026-06-29 21:14:30.319582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '557e476656e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
